### ISSUE TITLE
Issue In Verify Check: Error "Response verification failed"/"Invalid Token"

### ISSUE THREAD

**Issue by Suresh1988** [Nexmo/verify-javascript-sdk#4]
Hi,

Thanks for the wonderful sdk. It helps me to integrate very easily with nodejs.I am developing an web application using hapijs. In which , i am facing an issue after receiving the sms from nexmo, i retrieve the pin code from the UI and make the request to the nexmo using the Verfiyclient with app id and secret key as follows

```
var NV=new NexmoVerify({
    appId:APP_ID,
    sharedSecret:SECRET_KEY
});
 var ph_number="+"+data.number;//sample number for india as well as US such as +91xxxxxxxxxx, +1xxxxxxxxxx
            var code=data.code; //6 digit code
            NV.verifyCheck({
                number: ph_number,
                code: code
            }).then(function(status) {
                console.log(status);
            }, function(error){
                console.log(error);
            });
```

After calling the above function, in console i am receiving the following error message such as 
"Response verification failed".

Some times i am trying to make the call again, i am receiving "invalid token" error.

Please help me to resolve the issue.

Note: In the nexmo verify app portal, i have created the app_id and secret_key by unchecking the mandatory signature option and i select scope as Phone number, deviceid and app id

**Comment by LisaRoskam** [comment]
Hello Shuresh,

Glad to hear you are generally happy with this SDK. Because we would need identifying information from you to investigate this issue you would need to open a ticket directly with us by going to https://help.nexmo.com or sending email to support@nexmo.com.

Best regards,
Lisa Roskam
EMEA Support Manager
Nexmo

**Comment by lornajane** [comment]
Closed due to inactivity
