### ISSUE TITLE
Cannot find module 'bluebird' when bundling with browserify

### ISSUE THREAD

**Issue by leggetter** [Nexmo/verify-javascript-sdk#8]
``` bash
npm install verify-javascript-sdk
```

Ensure `browserify` is installed globally.

``` bash
npm -g i browserify
```

Create an `index.js` with contents:

``` js
var NexmoVerify = require('verify-javascript-sdk');
```

Run:

``` bash
$ browserify index.js -o bundle.js
```

See the error:

``` bash
Cannot find module 'bluebird' from '/Users/leggetter/tmp/verify/node_modules/native-or-bluebird'
```

**Comment by mtt87** [comment]
Curious I just tested and seems like if you `npm i bluebird` then browserify is happy.

Still it's not clear to me why `browserify` wants `bluebird` as it's not being used in the project.
It could be a good idea anyway to add it, to "standardize" the `Promise`.

😄

**Comment by mtt87** [comment]
I think I spotted the problem, when you `npm i verify-javascript-sdk`

``` bash
npm WARN deprecated native-or-bluebird@1.2.0: 'native-or-bluebird' is deprecated. Please use 'any-promise' instead.
```

And that dep is related to `popsicle 2.0.2`.
Just checked, the new version doesn't have anymore that dep so you could update popsicle to solve it but careful they are at `v8.2.0` I'm sure something has changed 😄

**Comment by mtt87** [comment]
👌  all fixed in `dev` branch, feel free to check & merge 
https://github.com/Nexmo/verify-javascript-sdk/tree/dev

**Comment by Growiel** [comment]
I'm having a very similar issue when trying to compile with Webpack (using the either master or dev branch):

`Cannot find module "child_process"`.

**Comment by lornajane** [comment]
Product no longer in use, closing this issue
