### ISSUE TITLE
Issue "Request Verification Failed"

### ISSUE THREAD

**Issue by athakral** [Nexmo/verify-javascript-sdk#9]
Hi, I think I found the bug with the sdk. As per following line, every request is supposed to have a header back "x-nexmo-response-signature"

https://github.com/Nexmo/verify-javascript-sdk/blob/master/src/shared.js#L33

but following request's

"{"url":"https://api.nexmo.com/sdk/verify/json?app_id=2882fd9c-d3ab-4cbc-8c3e-7dfcba…puKx7XMXj3kuh1LjuRVphL3XfOsAmYA%3D%3D&sig=fd213fb18774f34753c9de2dde2734dc","headers":{"Content-type":"application/x-www-form-urlencoded","Content-Encoding":"UTF-8","X-NEXMO-SDK-OS-FAMILY":"JS","X-NEXMO-SDK-REVISION":"0.2","Accept":"*/*","User-Agent":"https://github.com/blakeembrey/popsicle","Accept-Encoding":"gzip,deflate"},"body":null,"options":{},"timeout":0,"method":"GET"}"

response is 

"{"url":"https://api.nexmo.com/sdk/verify/json?app_id=2882fd9c-d3ab-4cbc-8c3e-7dfcba…puKx7XMXj3kuh1LjuRVphL3XfOsAmYA%3D%3D&sig=fd213fb18774f34753c9de2dde2734dc","headers":{"Access-Control-Allow-Headers":"X-NEXMO-SDK-OS-FAMILY,X-NEXMO-SDK-OS-REVISION,X-NEXMO-SDK-REVISION,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Encoding","Access-Control-Allow-Methods":"GET, OPTIONS","Access-Control-Allow-Origin":"*","Access-Control-Expose-Headers":"X-NEXMO-RESPONSE-SIGNATURE","Cache-Control":"max-age=1","Content-Disposition":"attachment; filename=\"api.txt\"","Content-Type":"application/json; charset=UTF-8","Date":"Tue, 27 Sep 2016 21:11:10 GMT","Server":"nginx","Strict-Transport-Security":"max-age=31536000; includeSubdomains","X-Content-Type-Options":"nosniff","X-Frame-Options":"deny","X-XSS-Protection":"1; mode=block;","Content-Length":"114","Connection":"close"},"body":{"result_code":0,"result_message":"OK","timestamp":"1475010670","user_status":"verified"},"status":200,"statusText":"OK"}"

Which actually doesn;t have it and thats why the sdk gives the error, "Request Verification Failed"

https://github.com/Nexmo/verify-javascript-sdk/blob/master/src/verify.js#L75 

Can someone look into that. 

Regards

**Comment by athakral** [comment]
these json objects are dump and urls might not be correct. But one particular request is not responding with that header and that is causing sdk to give this error.

**Comment by wrousseau** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue](https://trello.com/c/IXTrfQxQ/8-issue)

**Comment by wrousseau** [comment]
Hi @athakral! Sorry for the delay. There was an issue for certain apps where the back-end did not indeed send back this header. If you haven't fixed the issue already, could you try recreating an app and see if it works now?

Just tested doing that and it's working as expected. Closing the issue but feel free to reopen it if you have the issue.
